### ISSUE TITLE
Disable default highlight settings

### ISSUE THREAD

**Issue by jd-solanki** [fabiospampinato/vscode-highlight#84] opened 2021-12-15 07:20 UTC
Hi,

I really love this plugin but the issue is, it is highlighting my todos which I don't want. I already use [another todo extension](https://marketplace.visualstudio.com/items?itemName=ExodiusStudios.comment-anchors) which highlights the todos and provides extra features.

I want to disable default highlighting regex (settings). I tried removing it from my settings but recently I updated vscode and it appeared again.

Regards.

**Comment by fabiospampinato** [comment] 2022-02-16 05:58
@jd-0001 don't they disappear as soon as you provide some settings of your own?

**Comment by jd-0001** [comment] 2022-02-17 05:01
I only use this extension in certain projects so settings are not tweaked.

However, as per your comment, I have updated global settings to:
```json
"highlight.regexes": {},
```

I will reopen this issue if found any unexpected behavior.

Thanks for your response :)

**Comment by ctf0** [comment] 2022-04-26 21:23
same here, i have 
```json
"highlight.regexes": {
        "((?:<!-- *)?(?:#|// @|//|./\\*+|<!--|--|\\* @|{!|{{!--|{{!) *TODO(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": {
            "filterFileRegex": ".*(?<!CHANGELOG.md)$",
            "decorations": [
                {
                    "overviewRulerColor": "#ffcc00",
                    "backgroundColor": "#ffcc00",
                    "color": "#1f1f1f",
                    "fontWeight": "bold"
                },
                {
                    "backgroundColor": "#ffcc00",
                    "color": "#1f1f1f"
                }
            ]
        },
        "((?:<!-- *)?(?:#|// @|//|./\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:FIXME|FIX|BUG|UGLY|DEBUG|HACK)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": {
            "filterFileRegex": ".*(?<!CHANGELOG.md)$",
            "decorations": [
                {
                    "overviewRulerColor": "#cc0000",
                    "backgroundColor": "#cc0000",
                    "color": "#1f1f1f",
                    "fontWeight": "bold"
                },
                {
                    "backgroundColor": "#cc0000",
                    "color": "#1f1f1f"
                }
            ]
        },
        "((?:<!-- *)?(?:#|// @|//|./\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:REVIEW|OPTIMIZE|TSC)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": {
            "filterFileRegex": ".*(?<!CHANGELOG.md)$",
            "decorations": [
                {
                    "overviewRulerColor": "#00ccff",
                    "backgroundColor": "#00ccff",
                    "color": "#1f1f1f",
                    "fontWeight": "bold"
                },
                {
                    "backgroundColor": "#00ccff",
                    "color": "#1f1f1f"
                }
            ]
        },
        "((?:<!-- *)?(?:#|// @|//|./\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:IDEA)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": {
            "filterFileRegex": ".*(?<!CHANGELOG.md)$",
            "decorations": [
                {
                    "overviewRulerColor": "#cc00cc",
                    "backgroundColor": "#cc00cc",
                    "color": "#1f1f1f",
                    "fontWeight": "bold"
                },
                {
                    "backgroundColor": "#cc00cc",
                    "color": "#1f1f1f"
                }
            ]
        }
    }
```
that keeps getting added no matter what i do

**Comment by ctf0** [comment] 2022-04-26 21:26
@jd-0001 to disable it should be 
```json
"highlight.regexes": {
        "": ""
    }
```

because of https://github.com/fabiospampinato/vscode-highlight/blob/a112630b3517c6b35fb5f2532199d1be509b76e4/src/config.ts#L22

**Comment by jd-0001** [comment] 2022-04-27 04:45
Thanks for the workaround @ctf0 

Another workaround (I think this is normal) is to just disable the extension and only enabled it where I was using it and fortunately I overrides the settings where I use it :)

**Comment by SkryptX** [comment] 2023-01-27 22:31
Still a problem... Would be nice to have a fix... In my opinion there shouldn't even be a default anyway, but it's probably too late for that since the bug already became a feature :(

**Comment by fabiospampinato** [comment] 2023-01-31 15:25
> Still a problem... Would be nice to have a fix... 

Setting this in your global settings should "fix" it:

```ts
"highlight.regexes": {
  "": ""
}
```

> In my opinion there shouldn't even be a default anyway

Yeah it probably shouldn't, I think I made a mistake by setting some default configs, but some people thought this extension was meant to highlight todos by default or something.

> but it's probably too late for that since the bug already became a feature :(

Possibly yeah. Setting that global setting should get rid of the problem though, I think.

Closing for lack of a better option. Perhaps the default configuration will be deleted in a v2 release.

**Closed by fabiospampinato** 2023-01-31 15:25 UTC
Labels: bug
