### ISSUE TITLE
Extension host keeps crashing

### ISSUE THREAD

**Issue by itsMik4n** [fabiospampinato/vscode-highlight#48] opened 2020-04-11 13:46 UTC
Whenever I try to save any file, it takes a while, then all my extensions stop working and I get a "Extension host terminated"
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

```
bootstrap-window.js:209 [uncaught exception]: Error: write EPIPE
onUnexpectedError @ bootstrap-window.js:209
bootstrap-window.js:212 Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83)
onUnexpectedError @ bootstrap-window.js:212
events.js:180 Uncaught Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83)
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
```

What could it be? The extension was working just fine for the first hour before this started happening.

**Comment by fabiospampinato** [comment] 2020-04-11 13:54
What happens when you disable the extension?

**Comment by itsMik4n** [comment] 2020-04-11 14:32
When I disable the extension, everything works normally. 
I only have following extensions: Auto Close Tag, Python, Live Share, Polacode (and Highlight obviously) so I don't think there's a conflict.. I have not been using VS Code for long and didn't really change any default settings, so that shouldn't be the problem either.
I am running VS Code 1.44.0 on macOS Catalina.

```{
    "window.zoomLevel": 0,
    "[xml]": {},
    "highlight.decorations": {
    
    },
    "highlight.regexes": {
        // regexes for filtering xml tags
},
"auto-close-tag.SublimeText3Mode": true,
"workbench.colorTheme": "SynthWave '84"
}```

**Comment by disco0** [comment] 2020-04-16 11:24
I've beem getting that same error as well on Insiders this last week, haven't been able to figure it out either.  Only crashing with with Insiders atm, and I've had hundreds of lines of highlight config running fine until this so might be something else

**Comment by fabiospampinato** [comment] 2020-04-17 22:26
>         // regexes for filtering xml tags

@itsMik4n What are the actual regexes there?

I'd be useful if anybody can provide a configuration and file that reproduces the issue, otherwise there isn't much that I can do about it right now.

**Comment by fabiospampinato** [comment] 2021-04-02 17:41
Closing as I can't reproduce this, happy to reopen once somebody provides a repro.

**Closed by fabiospampinato** 2021-04-02 17:41 UTC
Labels: needs-more-info
