### ISSUE TITLE
Ignore comments

### ISSUE THREAD

**Issue by d0ob** [fabiospampinato/vscode-highlight#80] opened 2021-10-02 12:31 UTC
Hello there !

Is the highlight «token sensitive» ?
I am wondering if it is possible for the extension to ignore comments and strings ? 
( Highlighting «example» in code but not in comments nor strings, I mean. )
I’ve read the documentation and description, but did not find. 
I doubt sadly, supposing that a setting would already exist, but I wanted to ask to know for sure !

Though, thanks to said documentation/description, this GitHub, and the well-made of the extension : I now have the exact result I wanted to achieve when I searched online and found about your extension  ! Thanks much !

**Comment by fabiospampinato** [comment] 2022-02-16 06:01
I don't think it's possible 🤔 In any case this is a duplicate of https://github.com/fabiospampinato/vscode-highlight/issues/86

**Closed by fabiospampinato** 2022-02-16 06:01 UTC
